### ISSUE TITLE
Show Profile links only by hovering on the photo 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/gci17.fossasia.org#306]
### Expected results
Profile links will be visible only when one hovers on a Mentor/student/contributor's photo.
Please go through [https://codeheat.org/](https://codeheat.org/)

### Actual results
At present, Profile links are always visible

### Screenshot of the issue
**Actual**
![image](https://user-images.githubusercontent.com/24358501/33982717-8858c152-e0d7-11e7-9924-9ce395258c3b.png)
**Expected**
![image](https://user-images.githubusercontent.com/24358501/33982908-5d525cce-e0d8-11e7-87aa-507751cfd522.png)

**Comment by shikhar-scs** [comment]
On it.

**Comment by shikhar-scs** [comment]
I have found the exact places to make the respective changes and am also about to achieve them. However, this project being in ruby is proving to be a bit of a hindrance. I have since the beginning worked in NodeJS. Thus, after the changes i am unable to actually view them .

Basically setting up an executable gem is the main problem right now. Any help apart from the readme of linux installation

**Comment by shikhar-scs** [comment]
@anshumanv 
I have made the required changes and this is how they reflect.

The index page:
![The main index page](https://user-images.githubusercontent.com/25258877/34070113-91a3d3a0-e285-11e7-98b7-f5ed30e4f4db.png)

The load more directed mentors page
![The load more mentors page](https://user-images.githubusercontent.com/25258877/34070138-e59c1346-e285-11e7-9a3f-91d7a9abc1e6.png)

If these changes are acceptable should I do something similar for contributors too?

P.S. The icons turned black because I am hovering on them

**Comment by abishekvashok** [comment]
Can you make the black tint full width of the pic. Like how it is done in other fossasia sites?

**Comment by shikhar-scs** [comment]
@abishekvashok 
I tried that too but personally I think this one looks better. Ok I'll put that one.

**Comment by shikhar-scs** [comment]
Does it look better now?

index page
![new1](https://user-images.githubusercontent.com/25258877/34070539-33b37b3e-e28e-11e7-9a20-c4baab6abde9.png)

more page 
![new2](https://user-images.githubusercontent.com/25258877/34070545-41146b80-e28e-11e7-9b9b-ed1a905f225f.png)

And yes I've also set a transition time so that the change looks smooth

**Comment by abishekvashok** [comment]
@shikhar-scs please make a  PR! It looks good.

**Comment by ParthS007** [comment]
@shikhar-scs  very good 🎉  second one looks good , please change GitHub icon it not looks good

**Comment by shikhar-scs** [comment]
OK I'll do that too . Any other changes to be made?
Thanku for such reviews btw

**Comment by shikhar-scs** [comment]
@ParthS007  Sadly, themify icons provides only this github icon .
